# Generated by Django 5.1.15 on 2026-08-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Seeds', 'Seeds'), ('Fertilizers', 'Fertilizers'), ('Pesticides', 'Pesticides'), ('Equipment', 'Equipment'), ('Fuel', 'Fuel'), ('Crops', 'Crops')], default='Fertilizers', max_length=50)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('stock', models.IntegerField(default=100)),
                ('reorder_level', models.IntegerField(default=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
