# Generated by Django 5.1.15 on 2026-08-13 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=200)),
                ('crop_affected', models.CharField(default='General', max_length=100)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('severity', models.CharField(default='Medium', max_length=20)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('treatment_guidance', models.JSONField(default=list)),
                ('preventive_measures', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('diagnosed_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('land', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses', to='farms.land')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-diagnosed_at'],
            },
        ),
    ]
