# Generated by Django 5.1.15 on 2026-08-13 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('crop_name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity available (e.g. 50 Quintals / 500 kg)', max_digits=10)),
                ('unit', models.CharField(default='Quintals', max_length=20)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(help_text='District / State / City', max_length=200)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Sold', 'Sold'), ('Closed', 'Closed')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=150)),
                ('buyer_contact', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('offered_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='marketplace.marketplacelisting')),
            ],
        ),
    ]
