# Generated by Django 5.1.15 on 2026-08-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('scheme_type', models.CharField(choices=[('portal', 'Government Portal'), ('helpline', 'Emergency Helpline'), ('subsidy', 'Insurance & Subsidy'), ('advisory', 'Weather & Crop Advisory')], default='subsidy', max_length=50)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('min_land_acreage', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('max_land_acreage', models.DecimalField(decimal_places=2, default=1000.0, max_digits=6)),
                ('target_state', models.CharField(default='All', max_length=100)),
                ('crop_category', models.CharField(default='All', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
