# Generated by Django 5.1.15 on 2026-08-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('season', models.CharField(choices=[('Kharif', 'Kharif (Monsoon: Jun-Oct)'), ('Rabi', 'Rabi (Winter: Nov-Mar)'), ('Zaid', 'Zaid (Summer: Apr-May)'), ('All Season', 'All Season')], default='All Season', max_length=20)),
                ('optimal_ph_min', models.FloatField(default=6.0)),
                ('optimal_ph_max', models.FloatField(default=7.5)),
                ('target_nitrogen', models.FloatField(help_text='Target N requirement in kg/acre')),
                ('target_phosphorus', models.FloatField(help_text='Target P requirement in kg/acre')),
                ('target_potassium', models.FloatField(help_text='Target K requirement in kg/acre')),
                ('water_requirement', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('frost_sensitive', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
