# Generated by Django 5.1.15 on 2026-08-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
