# Generated by Django 5.1.15 on 2026-08-08 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('acreage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('soil_type', models.CharField(choices=[('Alluvial', 'Alluvial Soil'), ('Black', 'Black Soil'), ('Red', 'Red Soil'), ('Loamy', 'Loamy Soil'), ('Clay', 'Clay Soil'), ('Sandy', 'Sandy Soil'), ('Laterite', 'Laterite Soil')], default='Loamy', max_length=50)),
                ('location_name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoilData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.FloatField(help_text='Soil pH (e.g. 6.5)')),
                ('nitrogen', models.FloatField(help_text='Nitrogen in ppm')),
                ('phosphorus', models.FloatField(help_text='Phosphorus in ppm')),
                ('potassium', models.FloatField(help_text='Potassium in ppm')),
                ('organic_carbon', models.FloatField(help_text='Organic Carbon in %')),
                ('moisture', models.FloatField(help_text='Moisture in %')),
                ('sample_date', models.DateField()),
                ('lab_reference', models.CharField(default='#000001', max_length=50)),
                ('tested_by', models.CharField(default='Central Agri Lab', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_records', to='farms.land')),
            ],
        ),
    ]
